env:
# - GHCVER=7.6.1
# - GHCVER=7.6.2
# - GHCVER=7.6.3
# - GHCVER=7.8.1
 - GHCVER=7.8.2
# - GHCVER=head

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.18/bin:$PATH

install:
 - cabal update
 - cabal sandbox init
 - cabal install hpc-coveralls --bindir=$HOME/.cabal/bin/
 - cabal sandbox delete
 - cabal install happy
 - cabal install --only-dependencies --enable-tests --constraint 'process-conduit < 1.2.0' --constraint 'attoparsec-conduit < 1.1.0'

script:
 - cabal configure --enable-tests -v2 --enable-library-coverage  # -v2 provides useful information for debugging
 - cabal build   # this builds all libraries and executables (including tests/benchmarks)
 - run-cabal-test
 - cabal check
 - cabal sdist   # tests that a source-distribution can be generated

 - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi

after_script:
  - cd ../
  - pwd
  - ls dist/hpc/mix
  - ls dist/hpc/mix/test-prefork
  - ls dist/hpc/mix/test-prefork-server
  - ls dist/hpc/mix/prefork-0.0.7
  - ls dist/hpc/mix/prefork-0.0.7/prefork-0.0.7
  - cat dist/hpc/mix/test-prefork/Main.mix
  - cat dist/hpc/mix/test-prefork/Constant.mix
  - cat dist/hpc/mix/test-prefork/Util.mix
  - cat dist/hpc/mix/test-prefork-server/Main.mix
  - cat dist/hpc/mix/test-prefork-server/Constant.mix
  - cat dist/hpc/mix/prefork-0.0.7/prefork-0.0.7/System.Prefork.Class.mix
  - cat dist/hpc/mix/prefork-0.0.7/prefork-0.0.7/System.Prefork.Settings.mix
  - cat dist/hpc/mix/prefork-0.0.7/prefork-0.0.7/System.Prefork.Main.mix
  - cat dist/hpc/mix/prefork-0.0.7/prefork-0.0.7/System.Prefork.mix
  - hpc-coveralls --exclude-dir=test test-prefork test-prefork-server
